apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:openshift:scc:scc-logging-operator
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - scc-logging-operator
  resources:
  - securitycontextconstraints
  verbs:
  - use
